name: agora_market_dart_sdk
description: A Dart SDK for AgoraMarket API
version: 1.0.0
publish_to: "none"

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dio: ^5.4.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1
  one_of_serializer: ^1.0.0
  intl: ^0.18.0

dev_dependencies:
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  test: ^1.24.9
  lints: ^5.1.1

dependency_overrides:
  analyzer: ">=5.12.0 <7.0.0"
