name: agora_market_dart_sdk
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0
  built_value: ^8.10.1
  built_collection: ^5.1.1
  json_annotation: ^4.8.1
  fixnum: ^1.1.0
  collection: ^1.18.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.0
  build_runner: ^2.5.3
  json_serializable: ^6.9.5
  built_value_generator: ^8.10.1
  source_gen: ^2.0.0
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true 