name: agora_market_dart_sdk
description: A Dart SDK for AgoraMarket API
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dio: ^5.4.0
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  built_value: ^8.9.0
  built_collection: ^5.1.1
  one_of_serializer: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  built_value_generator: ^8.9.0
  test: ^1.24.9
  lints: ^5.1.1 